#!/bin/sh

# 该脚本通过替换原机的Factory分区，即无线校准分区来提高无线射频功率，改善无线信号；替换文件来自H3C NX30 pro无线校准文件。
# 替换后2.4G无线功率提高至25dbm，5G无线功率提高至24dbm。

# 复制H3C NX30 pro无线校准文件
cp /lib/firmware/MT7981_iPAiLNA_EEPROM.bin /tmp/MT7981_iPAiLNA_EEPROM.bin

# 提取原机MAC信息、写入H3C NX30 pro无线校准文件
dd if=/dev/mtd2 of=/tmp/MT7981_iPAiLNA_EEPROM.bin bs=1 seek=4 skip=4 count=44 conv=notrunc

# 将修改后无线校准文件写入Factory分区
mtd write /tmp/MT7981_iPAiLNA_EEPROM.bin /dev/mtd2
rm /tmp/MT7981_iPAiLNA_EEPROM.bin

exit 0
